server:
  port: 8081
spring:
  application:
    name: metabase-spring-demo
  datasource:
    url: "jdbc:mysql://localhost:3306/metabase_spring_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
    username: "myuser"
    password: "secret"
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
  flyway:
    baseline-on-migrate: true